# Generated by Django 5.0.3 on 2024-05-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=models.FileField(blank=True, null=True, upload_to='driver_photos/'),
        ),
    ]
