# Generated by Django 5.0.3 on 2024-04-18 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_driving', models.FloatField()),
                ('top_left_x', models.FloatField()),
                ('top_left_y', models.FloatField()),
                ('bottom_right_x', models.FloatField()),
                ('bottom_right_y', models.FloatField()),
                ('center_x', models.FloatField()),
                ('center_y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('masks', models.JSONField(blank=True, null=True)),
                ('keypoints', models.JSONField(blank=True, null=True)),
                ('probabilities', models.JSONField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reports')),
            ],
        ),
    ]
