# Generated by Django 4.1 on 2024-04-28 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("report", "0003_alter_driver_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportdetails",
            old_name="safe_driving",
            new_name="confidence",
        ),
        migrations.AddField(
            model_name="reportdetails",
            name="label",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reports",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
