# Generated by Django 4.1 on 2024-04-28 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("report", "0006_alter_reports_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportdetails",
            old_name="confidence",
            new_name="safe_driving",
        ),
        migrations.RemoveField(
            model_name="reportdetails",
            name="label",
        ),
        migrations.RemoveField(
            model_name="reports",
            name="user",
        ),
        migrations.AlterField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
