# Generated by Django 4.1 on 2024-04-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0008_trips_user_alter_driver_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trips",
            name="user",
        ),
    ]
