# Generated by Django 4.1 on 2024-04-28 02:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0010_reports_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
