# Generated by Django 4.1 on 2024-04-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0011_reports_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="driver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.driver",
            ),
            preserve_default=False,
        ),
    ]
