# Generated by Django 4.1 on 2024-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_inside_file",
                    models.FileField(upload_to="uploads/", verbose_name="In-car File"),
                ),
                (
                    "car_outside_file",
                    models.FileField(upload_to="uploads/", verbose_name="Out-car File"),
                ),
            ],
        ),
    ]
